#!/bin/bash

VENV_VERSION="1.11.4"
VENV_DIR="virtualenv-$VENV_VERSION"
VENV_ARCHIVE="$VENV_DIR.tar.gz"
VENV_URL="https://pypi.python.org/packages/source/v/virtualenv/$VENV_ARCHIVE"

PROJECT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )"
cd $PROJECT_DIR

cmd_exists () {
    command -v $1 >/dev/null 2>&1
}

if cmd_exists python3; then
    PYTHON=python3
    PY3=true
elif cmd_exists python; then
    PYTHON=python
    PY3=false
else
    echo "Requires Python."
    echo "Download at https://www.python.org/"
    exit
fi

if cmd_exists virtualenv; then
    virtualenv --python=$PYTHON $PROJECT_DIR/venv
else
    if cmd_exists wget; then
        wget $VENV_URL
    elif cmd_exists curl; then
        curl -O $VENV_URL
    else
        echo "Setup requires Virtualenv."
        echo "Download at $VENV_URL"
        echo "Extract with:"
        echo "    tar xzf $VENV_ARCHIVE"
        echo "Install with:"
        echo "    cd $VENV_DIR"
        echo "    sudo $PYTHON setup.py install"
        echo "Then rerun this bootstrap script."
        exit
    fi
    if ! [ $? -eq 0 ]; then
        echo "Error downloading Virtualenv package."
        exit
    fi
    tar xzf $VENV_ARCHIVE
    cd $VENV_DIR
    $PYTHON virtualenv.py $PROJECT_DIR/venv
fi
if ! [ $? -eq 0 ]; then
    echo "Error setting up virtual environment."
    exit
fi

cd $PROJECT_DIR
venv/bin/pip install -r requirements.txt
if ! [ $? -eq 0 ]; then
    echo "Error installing requirements."
    exit
fi

echo "Bootstrap completed successfully."
